# Generated by Django 5.1.6 on 2025-03-01 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professeur',
            name='classes',
            field=models.ManyToManyField(related_name='professeurs', to='App.classe'),
        ),
    ]
